// creating an array and passing the number, questions, options, and answers
let questions = [
    {
    numb: 1,
    question: " What is the primary environmental concern associated with improper disposal of e-waste?",
    answer: "All of the above",
    options: [
      "Air pollution",
      "Soil contamination",
      "Water pollution",
      "All of the above"
    ]
  },
  {
    numb: 2,
    question: "Which of the following materials is commonly found in electronic devices and can be recycled?",
    answer: "Copper",
    options: [
      "Glass",
      "Copper",
      "Plastic",
      "Styrofoam"
    ]
  },
    {
    numb: 3,
    question: "Which of the following should not be disposed of in regular trash bins?",
    answer: "Used batteries",
    options: [
      "Old clothing",
      "Broken glass",
      "Used batteries",
      "Food scraps"
    ]
  },
    {
    numb: 4,
    question: "What is the primary objective of proper e-waste management?",
    answer: "Protecting human health and the environment",
    options: [
      "Maximizing profit from discarded electronics",
      "Protecting human health and the environment",
      "Reducing electronic waste to zero",
      "Promoting consumerism"
    ]
  },
    {
    numb: 5,
    question: "Which of the following is NOT an example of e-waste?",
    answer: "Plastic bottles",
    options: [
      "Old laptops",
      "Used Batteries",
      "Broken smartphones",
      "Plastic bottles"
    ]
  },
  {
    numb: 6,
    question: "What is the first step individuals should take when disposing of e-waste?",
    answer: "Check for recycling options",
    options: [
      "Sell it online",
      "Throw it away",
      "Donating it",
      "Check for recycling options"
    ]
  },
  {
    numb: 7,
    question: "What is one of the main causes of e-waste?",
    answer: "Population Growth",
    options: [
      "Population Growth",
      "Pollution",
      "Global Warming",
      "Climate Change"
    ]
  },
  {
    numb: 8,
    question: "Which is not a cause of e-waste?",
    answer: "Population is becoming more poorer",
    options: [
      "Growth of technology",
      "Population is getting smarter",
      "Population is becoming more poorer",
      "People don't want to take the time to dispose of e-waste properly"
    ]
  },
  {
    numb: 9,
    question: "What is e-waste?",
    answer: "Waste generated by electronic devices",
    options: [
      "Waste generated by elephants",
      "Waste generated by electronic devices",
      "Waste generated by energy consumption",
      "Waste generated by earthquakes"
    ]
  },
  {
    numb: 10,
    question: "How does e-waste recycling benefit the environment?",
    answer: "By conserving natural resources",
    options: [
      "By increasing pollution",
      "By generating more waste",
      "By conserving natural resources",
      "By depleting natural resources"
    ]
  },
  // you can uncomment the below codes and make duplicate as more as you want to add question
  // but remember you need to give the numb value serialize like 1,2,3,5,6,7,8,9.....

  //   {
  //   numb: 6,
  //   question: "Your Question is Here",
  //   answer: "Correct answer of the question is here",
  //   options: [
  //     "Option 1",
  //     "option 2",
  //     "option 3",
  //     "option 4"
  //   ]
  // },
];